<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice <?= esc($sale->invoice_no) ?></title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #222; }
        .top { width: 100%; margin-bottom: 14px; }
        .top table { width: 100%; border-collapse: collapse; }
        .top td { vertical-align: top; border: 0; padding: 0; }
        h2 { margin: 0 0 8px 0; }
        p { margin: 2px 0; }
        table.invoice { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.invoice th, table.invoice td { border: 1px solid #ddd; padding: 7px; }
        table.invoice th { background-color: #f5f5f5; }
        .text-right { text-align: right; }
        .total { font-weight: bold; }
        .notes { margin-top: 12px; }
    </style>
</head>
<body>
    <div class="top">
        <table>
            <tr>
                <td>
                    <h2>Sales Invoice</h2>
                    <p><strong>Invoice No:</strong> <?= esc($sale->invoice_no) ?></p>
                    <p><strong>Date:</strong> <?= esc(date('Y-m-d H:i', strtotime($sale->sale_date))) ?></p>
                </td>
                <td class="text-right">
                    <p><strong>Customer:</strong> <?= esc($sale->customer_name ?: 'Walk-in Customer') ?></p>
                    <p><strong>Generated By:</strong> <?= esc($printedBy) ?></p>
                </td>
            </tr>
        </table>
    </div>

    <table class="invoice">
        <thead>
            <tr>
                <th>Product</th>
                <th>Weight</th>
                <th>Qty</th>
                <th>Unit Price</th>
                <th>Subtotal</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($items as $item): ?>
                <tr>
                    <td><?= esc($item->product_name) ?></td>
                    <td><?= esc($item->cylinder_weight ?? '-') ?></td>
                    <td><?= (int) $item->quantity ?></td>
                    <td class="text-right"><?= esc(format_currency((float) $item->unit_price)) ?></td>
                    <td class="text-right"><?= esc(format_currency((float) $item->subtotal)) ?></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="4" class="text-right total">Total</td>
                <td class="text-right total"><?= esc(format_currency((float) $sale->total_amount)) ?></td>
            </tr>
        </tbody>
    </table>

    <?php if (!empty($sale->notes)): ?>
        <p class="notes"><strong>Notes:</strong> <?= esc($sale->notes) ?></p>
    <?php endif; ?>
</body>
</html>
