<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sales Report - <?= esc(strtoupper($preset ?: 'custom')) ?></title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #222; }
        h2 { margin: 0 0 8px 0; }
        p { margin: 2px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 7px; }
        th { background-color: #f5f5f5; }
        .text-right { text-align: right; }
        .total { font-weight: bold; }
        .sale-items { margin: 3px 0; font-size: 11px; }
    </style>
</head>
<body>
    <h2>Sales Report (<?= esc(strtoupper($preset ?: 'CUSTOM')) ?>)</h2>
    <p><strong>Date Range:</strong> <?= esc(($dateFrom ?: 'Start') . ' to ' . ($dateTo ?: 'End')) ?></p>
    <p><strong>Generated By:</strong> <?= esc($printedBy) ?></p>

    <?php if ($detailed): ?>
        <table>
            <thead>
                <tr>
                    <th>Invoice No</th>
                    <th>Date</th>
                    <th>Customer</th>
                    <th>Items</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($sales as $sale): ?>
                <tr>
                    <td><?= esc($sale->invoice_no) ?></td>
                    <td><?= esc(date('Y-m-d H:i', strtotime($sale->sale_date))) ?></td>
                    <td><?= esc($sale->customer_name ?: 'Walk-in Customer') ?></td>
                    <td>
                        <?php foreach (($saleItemsMap[(int) $sale->id] ?? []) as $item): ?>
                            <div class="sale-items">
                                <?= esc($item->product_name) ?> (<?= (int) $item->quantity ?> x <?= esc(format_currency((float) $item->unit_price)) ?>)
                            </div>
                        <?php endforeach; ?>
                    </td>
                    <td class="text-right"><?= esc(format_currency((float) $sale->total_amount)) ?></td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td colspan="4" class="text-right total">Total Sales</td>
                <td class="text-right total"><?= esc(format_currency((float) $totalSalesAmount)) ?></td>
            </tr>
            </tbody>
        </table>
    <?php else: ?>
        <table>
            <thead>
                <tr>
                    <th>Period</th>
                    <th class="text-right">Total Sales</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?= esc(ucfirst($preset ?: 'Custom')) ?> Summary</td>
                    <td class="text-right"><?= esc(format_currency((float) $totalSalesAmount)) ?></td>
                </tr>
            </tbody>
        </table>
    <?php endif; ?>
</body>
</html>
